UPDATE ESTADOS 
SET NOME = 'Maranhão'
WHERE SIGLA = 'MA'

SELECT NOME FROM ESTADOS WHERE SIGLA = "MA"



UPDATE ESTADOS
SET POPULACAO = 11.32
WHERE SIGLA = "PR"

SELECT POPULACAO FROM ESTADOS WHERE SIGLA = "PR"