SELECT * FROM ESTADOS

INSERT INTO CIDADES (NOME, AREA, ESTADO_ID)
VALUES ('Campinas' , 795, 34)


INSERT INTO CIDADES (NOME, AREA, ESTADO_ID)
VALUES ('Niterói' , 133.9, 28)

INSERT INTO CIDADES (NOME, AREA, ESTADO_ID)
VALUES ('Caruaru' , 920.6, (SELECT ID FROM ESTADOS WHERE SIGLA = 'PE')
)

SELECT * FROM CIDADES
