SELECT * FROM ESTADOS

SELECT NOME,SIGLA FROM ESTADOS

SELECT NOME AS "Nome do Estado",SIGLA AS "Sigla do Estado" FROM ESTADOS

SELECT NOME,SIGLA,POPULACAO FROM ESTADOS 
WHERE REGIAO = "Sudeste"

SELECT NOME,POPULACAO FROM ESTADOS 
WHERE POPULACAO > 10 
ORDER BY POPULACAO 

