CREATE TABLE IF NOT EXISTS EMPRESAS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    CNPJ INT UNSIGNED UNIQUE KEY
);

-- CIDADES_EMPRESAS

CREATE TABLE IF NOT EXISTS EMPRESAS_UNIDADES (
    EMPRESA_ID INT UNSIGNED NOT NULL,
    CIDADE_ID INT UNSIGNED NOT NULL,
    SEDE TINYINT (1) NOT NULL,
    PRIMARY KEY (EMPRESA_ID, CIDADE_ID)
);
