-- CRIANDO TABELA ESTADO!


CREATE TABLE ESTADOS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    SIGLA VARCHAR(2) NOT NULL,
    REGIAO ENUM('NORTE' , 'SUDESTE' ,'NORDESTE','SUL','CENTRO-OESTE') NOT NULL,
    POPULACAO DECIMAL(5,2) NOT NULL,
    PRIMARY KEY(ID),
    UNIQUE KEY(NOME),
    UNIQUE KEY(SIGLA)
);



